// sanity/config/languages.ts
export const SUPPORTED_LANGUAGES = [
  { id: "en", title: "English" },
  { id: "fr", title: "Français" },
  { id: "de", title: "Deutsch" },
  { id: "es", title: "Español" },
  { id: "it", title: "Italiano" },
  { id: "pl", title: "Polski" },
  { id: "ro", title: "Română" },
  { id: "nl", title: "Nederlands" },
  { id: "pt", title: "Português" },
  { id: "cs", title: "Čeština" },
  { id: "sk", title: "Slovenčina" },
  { id: "hu", title: "Magyar" },
  { id: "bg", title: "Български" },
  { id: "hr", title: "Hrvatski" },
  { id: "sl", title: "Slovenščina" },
  { id: "lt", title: "Lietuvių" },
  { id: "lv", title: "Latviešu" },
  { id: "et", title: "Eesti" },
  { id: "fi", title: "Suomi" },
  { id: "sv", title: "Svenska" },
  { id: "el", title: "Ελληνικά" },
  { id: "mt", title: "Malti" },
  { id: "ga", title: "Gaeilge" },
];
